				<div class="copypic"><img src="images/cape-subpic1.jpg" /></div>
				<h3 class="subheader"><b>Volunteer</b><br />help our community</h3>
				<div class="subsideicon"><img src="images/cape_icon_community.png" /></div>
				<div class="maincopy">
				
                <p>Parent volunteers are integral to the success of CAPE. From an hour spent assisting in the classroom to 
                taking on teaching an entire mini course and everything in between, CAPE flourishes as parent involvement 
                increases. So much so that the charter authorizing CAPE to exist requests that each family volunteer for one 
                hour per week, which equates to approximately 40 hours every school year. CAPE understands parents have varying 
                schedules, so the CAPE PTSO helps coordinate the volunteer needs of the school with the availability of parents. 
                Please contact Kimberly Glasby (VP of Volunteers) mailto:<a href="mailto:volunteers@capeptso.org">volunteers@capeptso.org</a> 
                if you have questions or would like to be added to the distribution list for volunteer opportunities as they arise.<br /><br />
                
                Please be sure to log your hours into Keep N Track: 
                <a href="https:// knt3.keepntrack.com/HTML/KeepnTrackLogin.html?db=cape&version=2.71.23" target="_blank">
                http://cape.keepntrack.com</a><br /><br />

                <strong>A list of current volunteer opportunities is below:</strong><br /><br />

                8/22/2012 - We need people to stuff the first day of school packets from 9 until noon.<br />
                <a href="http://www.signupgenius.com/go/10C044AAFAA2DA64-stuff" target="_blank">
                www.SignUpGenius.com/go/10C044AAFAA2DA64-stuff/1973710</a></p>

                </div>