				<div class="copypic"><img src="images/cape_fund.jpg" /></div>
				<h3 class="subheader"><b>Fund Raising</b><br />help our community</h3>
				<div class="subsideicon"><img src="images/cape_icon_community.png" /></div>
				<div class="maincopy">
					
                    
                    <p>Fundraising is part of the mission of the CAPE PTSO.  On average, charter schools receive only 
                    about 75% of the funding that traditional district schools receive.  This varies by state, but 
                    the deficit is usually related to the fact that most charter schools are not eligible for facilities 
                    funding, so they must stretch the funding they do receive.  CAPE PTSO raises funds for the school 
                    to help close this funding gap, and to provide direct funding to teachers for classroom supplies, 
                    PE and music instruction, and to provide funding that helps make extracurricular activities like 
                    Mini-Courses and Day With an Author possible.</p>
                    
                    <p><strong>Fundraising Schedule for 2012/2013</strong></p>

                    <p>The fundraising calendar for the 2012/2013 school year will be updated as dates are firmed up.  
                    Also, other events like Family Night Out will be scheduled throughout the year so be sure to 
                    watch the Facebook status updates for information on these!  There are also yearlong fundraisers 
                    such as Box Tops and Friday lunches.</p>
                    
                    <p><strong>Sep 5, 2012 - CAPE-A-THON:</strong> participating students obtain sponsors (friends and family), and the 
                    amount raised is based on their participation in the event.  The kids have fun running an obstacle 
                    course and raise money for the school at the same time!</p>
                    
                    <p><strong><strong>Nov 6, 2012 - Adopt-A-Pole:</strong></strong> CAPE PTSO will be adopting a poling location on election day.  By staffing 
                    the location with all parent volunteers, CAPE PTSO receives a check from the county for the entire 
                    amount that would normally be used to pay the staffers.  Combining civic duty with fundraising for a 
                    great school - what a wonderful way to fundraise!</p>
                    
                    </p>Dec 3 - 7, 2012 - Book Fair: Come purchase books at a discounted rate and fundraise for CAPE at the same time!</p>

                    </p><strong>Feb 1, 2012 - Palooza!:</strong> A fun family event where the student participation makes this night a huge success!  
                    Parents are entertained by a student talent show, and a silent auction allows the parents to bid on classroom 
                    prepared and other donated items.</p>
                    
                    </p><strong>Mar 16, 2012 - Spring Boutique:</strong></p>
                    
                    </p><strong>May 17, 2012 - Spring Gala:</strong> This is an adult only evening with dinner, dancing, and an auction.  This year will be 
                    slightly different from years past with a new location (Maravilla Gardens) and a "Denim and Diamonds" theme.  Leave 
                    the kids at home and enjoy a fun night out!</p>
                    
                    </div>