				<div class="copypic"><img src="images/cape_board.jpg" /></div>
				<h3 class="subheader"><b>PTSO Executive Board</b><br />help our community</h3>
				<div class="subsideicon"><img src="images/cape_icon_justice.png" /></div>
				<div class="maincopy">
					
                    <p><strong>President:</strong> Brian Hill<br />
  <a href="mailto:president@capeptso.org">president@capeptso.org</a> <br /><br />
  <strong>VP Communications:</strong> Kelly Williams<br />
  <a href="mailto:communications@capeptso.org">communications@capeptso.org</a> <br /><br />
  <strong>VP Programs:</strong> Agha &ldquo;Ali&rdquo; Khan<br />
  <a href="mailto:programs@capeptso.org">programs@capeptso.org</a> <br /><br />
  <strong>VP Fundraising:</strong> Cindy Cogswell<br />and Cherish Stamper (co-VPs)<br />
  <a href="mailto:fundraising@capeptso.org">fundraising@capeptso.org</a> <br /><br />
  <strong>VP Volunteers:</strong> Kimberly Glasby<br />
  <a href="mailto:volunteers@capeptso.org">volunteers@capeptso.org</a> <br /><br />
  <strong>Secretary:</strong> Krista Furman<br />
  <a href="mailto:secretary@capeptso.org">secretary@capeptso.org</a> <br /><br />
  <strong>Treasurer:</strong> Nathalie Habash and<br />
  Yolanda Schardt (co-Treasurers)<br />
<a href="mailto:treasurer@capeptso.org">treasurer@capeptso.org</a></p>
                    
                    </div>