<div class="copypic"><img src="images/cape_homepic1.jpg" /></div>
<h3 class="subheader"><b>Welcome</b><br />to capeptso.org</h3>
<div class="home_create">
    <b>First time here?</b><br />
    <a href="/auth/register" class="create_account btn fr">Create an account</a>
</div>
<div class="maincopy">
	<p><strong>Welcome to the CAPE PTSO web site!</strong>  This site was created to foster communications between CAPE 
    parents and the CAPE PTSO in order to successfully perform the core missions of the CAPE PTSO: to 
    coordinate fundraising activities for CAPE, and to ensure parents are well informed of the many volunteer 
    opportunities at CAPE in order to meet their family volunteer requirements.  This site keeps parents and 
    the community informed on the happenings of CAPE PTSO, provides helpful links for parents, and serves as 
    a central communications point for PTSO related activities.  We want this site to be as useful as possible, 
    so we welcome feedback and suggestions on possible improvements and modifications.  Also, be sure to visit 
    CAPE's web site, <a href="http://www.camarillocharter.org/" target="_blank">www.camarillocharter.org</a> for school specific information like the CAPE Handbook, faculty 
    and staff biographies, enrollment forms, etc.</p>
</div>