				<div class="copypic"><img src="images/cape_agendas.jpg" /></div>
				<h3 class="subheader"><b>Agendas</b><br />help our community</h3>
				<div class="subsideicon"><img src="images/cape_icon_agenda.png" /></div>
				<div class="maincopy">
					
                    <p>The CAPE PTSO understands parents have many demands on their time, and are not always able to attend the PTSO meetings. 
                    Keeping the parents informed of PTSO activities is our priority, so the agendas and minutes for each meeting are posted here 
                    as soon as they are available.</p>
                    
                    <p align="left"><strong>PTSO General Meetings</strong></p>
                    
                        <p align="left">March 6, 2012 (<a href="http://www.camarillocharter.org/uploads/030612_Gen_Minutes.pdf" target="_blank">minutes PDF</a>)<br />
                          March 6, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_03_PTSO_GenAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          January 25, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_01_PTSO_GenAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          January 25, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_01_25_PTSO_GenMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          November 28, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_11_PTSOGenAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          November 28, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_11_28_PTSOGenMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          October 24, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_10_PTSOGenAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          October 24, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_10_24_PTSOGenMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          September 26, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_09_PTSOGenAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          September 26, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_09_26_PTSOGenMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          February 28, 2011 (<a href="http://www.camarillocharter.org/uploads/022811ptso_gagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          February 28, 2011 (<a href="http://www.camarillocharter.org/uploads/022811gen_min.pdf" target="_blank">minutes PDF</a>)<br />
                          December 13, 2010 (<a href="http://www.camarillocharter.org/uploads/121310ptso_gagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          November 15, 2010 (<a href="http://www.camarillocharter.org/uploads/111510gen_min.pdf" target="_blank">minutes PDF</a>)<br />
                          November 15, 2010 (<a href="http://www.camarillocharter.org/uploads/111510ptso_gagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          October 18, 2010 (<a href="http://www.camarillocharter.org/uploads/101810gen_min.pdf" target="_blank">minutes PDF</a>)<br />
                          October 18, 2010 (<a href="http://www.camarillocharter.org/uploads/101810ptso_gagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          September 9, 2010 (<a href="http://www.camarillocharter.org/uploads/090910gen_min.pdf" target="_blank">minutes PDF</a>)</p>
                        <p align="left"><strong>PTSO Executive Board Meetings</strong></p>
                        <p align="left">March 26, 2012 (<a href="http://www.camarillocharter.org/uploads/032612_Exec_Gen_Agenda.pdf" target="_blank">agenda PDF</a>)<br />
                          March 26, 2012 (<a href="http://www.camarillocharter.org/uploads/032612_Exec_Gen_Minutes.pdf" target="_blank">minutes PDF</a>)<br />
                          March 6, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_03_PTSO_ExecAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          March 6, 2012 (<a href="http://www.camarillocharter.org/uploads/030612_Exec_Minutes.pdf" target="_blank">minutes PDF</a>)<br />
                          January 25, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_01_PTSO_ExecAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          January 25, 2012 (<a href="http://www.camarillocharter.org/uploads/2012_01_25_PTSO_ExecMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          November 28, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_11_PTSOExecAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          November 28, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_11_28_PTSOExecMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          October 24, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_10_PTSOExecAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          October 24, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_10_24_PTSOExecMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          September 26, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_09_PTSOExecAgenda.pdf" target="_blank">agenda PDF</a>)<br />
                          September 26, 2011 (<a href="http://www.camarillocharter.org/uploads/2011_09_26_PTSOExecMinutes.pdf" target="_blank">minutes PDF</a>)<br />
                          February 28, 2011 (<a href="http://www.camarillocharter.org/uploads/022811ptso_xagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          February 28, 2011 (<a href="http://www.camarillocharter.org/uploads/022811exec_min.pdf" target="_blank">minutes PDF</a>)<br />
                          December 13, 2010 (<a href="http://www.camarillocharter.org/uploads/121310ptso_xagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          November 15, 2010 (<a href="http://www.camarillocharter.org/uploads/111510ptso_xagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          November 15, 2010 (<a href="http://www.camarillocharter.org/uploads/111510exec_min.pdf" target="_blank">minutes PDF</a>)<br />
                          October 18, 2010 (<a href="http://www.camarillocharter.org/uploads/101810ptso_xagenda.pdf" target="_blank">agenda PDF</a>)<br />
                          October 18, 2010 (<a href="http://www.camarillocharter.org/uploads/101810exec_min.pdf" target="_blank">minutes PDF</a>)<br />
                          September 9, 2010 (<a href="http://www.camarillocharter.org/uploads/090910exec_min.pdf" target="_blank">minutes PDF</a>)</p>
                                            </p>
                    
                    </div>