				<div class="copypic"><img src="images/cape_history.jpg" /></div>
				<h3 class="subheader"><b>History</b><br />September 5th, 2007</h3>
				<div class="subsideicon"><img src="images/cape_icon_history_sm.png" /></div>
				<div class="maincopy">
				
                <p>The Camarillo Academy of  Progressive Education (CAPE) was approved by the Oxnard Union High School  District on June 20 and opened on Sept. 5 for the 2007-08 school year. CAPE is  teaching students in grades K-8 with an educational philosophy that expands  upon the &ldquo;Open&rdquo; philosophy that thrived in Camarillo for over 30 years, first  at Bedford Open and then at Los Senderos Open.<br /><br />
  The mission of Camarillo Academy  of Progressive Education Charter School is to foster global, independent,  creative thinkers who feel confident in themselves, are willing to take risks,  and work cooperatively. Together the parents, students, and teachers create a  progressive environment that sparks imagination, ignites a love for learning,  and encourages each individual to be and do the best that he/she can; enabling  pupils to become self-motivated, competent, and life-long learners, equipped  for the challenges of the 21st Century.<br /><br />
  Please visit <a href="http://www.camarillocharter.org/" target="_blank">http://www.camarillocharter.org</a> for more information about CAPE.</p>	
                    
                </div>