<div class="hr_full"></div>
<div class="footer">
	<div class="footer_col">
		Copyright &copy; CAPE PTSO,<br />
        FED Tax ID 26-1160504<br />
        777 Aileen St.<br />
        Camarillo, CA 93010<br />
        805) 384-1415<br />
		<a href="mailto:info@capeptso.org">info@capeptso.org</a><br />
	</div>
	<div class="footer_col">
		<ul>
    		<li><a href="/index">Home</a></li>
    		<li><a href="/about">About PTSO</a></li>
    		<li><a href="/history">CAPE History</a></li>
    		<li><a href="/boardmembers">CAPE PTSO Board Members</a></li>
    		<li><a href="/volunteering">Volunteering</a></li>
		</ul>
	</div>
	<div class="footer_col">
		<ul>
    		<li><a href="/agendas">PTSO Meetings</a></li>
    		<li><a href="/fundraising">Fundraising</a></li>
    		<li><a href="/supporters">Supporters / Links</a></li>
    		<li><a href="/tools">Tools</a></li>
    		<li><a href="/contact">Contact Us</a></li>
    		<li><a href="/auth">Family Login</a></li>
		</ul>
	</div>
	<div class="clear"></div>
	<div class="deisngedby">
		<a href="http://www.805webdesigns.com"><img src="/images/805-web-designs.png" alt="805 Web Designs" /></a><br />
		Website developed and designed by: <a href="http://www.805webdesigns.com">805webdesigns.com</a>
	</div>
</div>