<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width" >
<meta name="description" content="">
<meta name="keywords" content="">

<link rel="stylesheet" type="text/css" media="screen" href="/css/layout.css">
<link rel="stylesheet" type="text/css" media="print" href="/css/layout_print.css">

<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>