<div class="nav">
	<ul>
		<li><a href="/index">Home</a></li>
		<li><a href="/about">About PTSO</a></li>
		<li><a href="/history">CAPE History</a></li>
		<li><a href="/boardmembers">CAPE PTSO Board Members</a></li>
		<li><a href="/volunteering">Volunteering</a></li>
		<li><a href="/agendas">PTSO Meetings</a></li>
		<li><a href="/fundraising">Fundraising</a></li>
		<li><a href="/supporters">Supporters / Links</a></li>
		<li><a href="/tools">Tools</a></li>
		<li><a href="/contact">Contact Us</a></li>
	</ul>
</div>