				<div class="copypic"><img src="images/cape_about.jpg" /></div>
				<h3 class="subheader"><b>About CAPE PTSO</b><br />Parents and teachers working together</h3>
				<div class="subsideicon"><img src="images/cape_icon_about_sm.png" /></div>
				<div class="maincopy">
					
                    <p>
                    The CAPE Parent-Teacher-Student Organization (PTSO) was created to serve two main goals: raise 
                    money for CAPE Charter School by coordinating fundraising activities, and to coordinate parent 
                    volunteers with the needs of the school.  By coordinating fundraising efforts throughout the year, 
                    both as individual events and year-long efforts, the CAPE PTSO is able to provide funding for programs 
                    and other efforts that would not otherwise be possible.<br /><br />
                    Parent volunteering is an integral part of the CAPE philosophy, and helping parents match their 
                    interests and availability with the needs of the school is imperative.  Over 16,000 parent volunteer 
                    hours were logged during the 2011-12 school year, and because of this educational programs like Mini 
                    Courses and  Day with an Author are possible, and fundraising efforts like Cape-a-thon and Friday 
                    Lunches are possible.<br /><br />
                    A more complete list of programs, fundraising efforts, and volunteer opportunities can be found on 
                    this web site.<br /><br />
                    CAPE PTSO is a 501(c)3 charitable organization and our Federal Tax ID is 26-1160504.<br /><br />
                    <strong>Who are the members of the CAPE PTSO?</strong><br />
                        Every parent, teacher, and student currently enrolled in CAPE are members of the CAPE PTSO.  
                        In addition, there is an elected board of officers that serves as the PTSO administration.  
                        These positions consist of President, Secretary, Treasurer, and VPs of Programs, Fundraising, 
                        Volunteering, and Communications. <br /><br />
                    <strong>Where are meetings held?</strong><br />
                        Meetings are normally held in the MPR at CAPE.<br /><br />
                    <strong>How often are meetings held?</strong><br />
                        General meetings are held on a monthly basis in order to comply with the CAPE PTSO bylaws 
                        that state the officers will meet on a monthly basis during the school year.<br /><br />
                    <strong>Who can attend the meetings?</strong><br />
                        Every parent, teacher, and student currently enrolled in CAPE are welcome and encouraged 
                        to attend. All meetings are open to all members &ndash; there are no closed sessions.<br /><br />
                    <strong>How formal are the meetings?</strong><br />
                        Robert's Rules of Order are used as the guidelines for running the meetings.  Although 
                        somewhat formal, it ensures that the agenda is adhered to and those who have requested 
                        to be on the agenda have time to speak.  There are areas in the agenda for non-agenda 
                        items to be discussed.<br /><br />
                    <strong>Who votes during the meetings?</strong><br />
                        It depends.  Some items, like approving the minutes from the previous meeting, only 
                        require a vote of the PTSO board members.  Other items, like approving the budget and 
                        changing the bylaws, are voted on by the PTSO general members.
                    
                    </p>
                    
                    </div>