				<div class="copypic"><img src="images/cape_contact.jpg" /></div>
				<h3 class="subheader"><b>Contact</b><br />communication is key</h3>
				<div class="subsideicon"><img src="images/cape_icon_contact.png" /></div>
				<div class="maincopy">
    				<p>Please feel free to contact us for any reason!  Suggestions for web site improvements?  Questions about fundraising or have an idea?</p>
    				<p>Questions about corporate sponsorship?  We're here for you!  
    				Please send us an e-mail at <a href="mailto:info@capeptso.org">info@capeptso.org</a> and we'll get back with you as soon as possible.</p>
    				<br />
    				<p>Camarillo Academy of Progressive Education<br />
    				777 Aileen Street - Camarillo, CA 93010<br />
    				<a href="tel:805-384-1415">805-384-1415</a> - Fax: <a href="tel:805-384-1473">805-384-1473</a></p>
    				<br />
    				<p>If you have any issues with this web site please contact the webmaster: <a href="mailto:larry@805webdesigns.com">larry@805webdesigns.com</a></p>
				</div>